# Generated by Django 4.2.11 on 2024-03-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
