# Generated by Django 4.2.11 on 2024-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
