# Generated by Django 4.2.11 on 2024-04-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
