"""
Django settings for ecom project.

Generated by "django-admin startproject" using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l=w4rw_@#gpl3p-fad@2&@ow-=_l=fyv2o_547q-lf0=bx+ulb" #os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don"t run with debug turned to TRUE in production! Should be False
DEBUG = False

ALLOWED_HOSTS = ["shoptop.click", "www.shoptop.click", "*"]

# Users can access your website, but without this setting, they can't make POST requests
CSRF_TRUSTED_ORIGINS = ["https://shoptop.click", "https://www.shoptop.click"] #http://ecom-dev.us-east-1.elasticbeanstalk.com/


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store", # django app
    "cart", # django app
    "mathfilters", 
    "account", # django app
    "crispy_forms", 
    "payment", # django app
    "storages"
]

CRISPY_TEMPLATE_PACK = "bootstrap4"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ecom.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "store.views.categories", #Updated
                "cart.context_processors.cart", # session handling
            ],
        },
    },
]

WSGI_APPLICATION = "ecom.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# he
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "static/media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USE_TLS = "True"

# Resources guide
EMAIL_HOST_USER = "aktran321@gmail.com" # - Enter your GMAIL Address for App password
EMAIL_HOST_PASSWORD = os.getenv("HOST_PW") # Enter your app password

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# AWS credentials:

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY")  # Access Key ID 
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_KEY")  # Secret Access Key ID

# S3 configuration settings:

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")  # Bucket Name

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_CUSTOM_DOMAIN = "%s.s3.amazonaws.com" % AWS_STORAGE_BUCKET_NAME

AWS_S3_FILE_OVERWRITE = False

ADMIN_MEDIA_PREFIX = "static/admin/"

"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""

# RDS Database Configuration


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "djangostore",
        "USER": "andy",
        "PASSWORD": os.getenv("AWS_RDS_PW"),
        "HOST": "djangostore-instance.cnlolruprcuj.us-east-1.rds.amazonaws.com",
        "PORT": "5432",
        }
    }

